Repository tteokguk-please/tteokguk-api, pull requests merged in 2024-01, with the labels that each got.

#11 [FEATURE] 회원가입 API
  build.gradle
  src/main/java/com/tteokguk/tteokguk/global/exception/error/ErrorResponse.java
  src/main/java/com/tteokguk/tteokguk/global/security/SecurityConfig.java
  src/main/java/com/tteokguk/tteokguk/member/application/AuthService.java
  src/main/java/com/tteokguk/tteokguk/member/application/dto/AppJoinRequest.java
  src/main/java/com/tteokguk/tteokguk/member/application/dto/AppJoinResponse.java
  src/main/java/com/tteokguk/tteokguk/member/domain/Inventory.java
  src/main/java/com/tteokguk/tteokguk/member/domain/Member.java
  src/main/java/com/tteokguk/tteokguk/member/domain/SimpleMember.java
  src/main/java/com/tteokguk/tteokguk/member/exception/AuthError.java
  src/main/java/com/tteokguk/tteokguk/member/infra/persistence/MemberRepository.java
  src/main/java/com/tteokguk/tteokguk/member/infra/persistence/SimpleMemberRepository.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/AuthController.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/dto/WebExistedResourceResponse.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/dto/WebJoinRequest.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/dto/WebJoinResponse.java
  src/main/java/com/tteokguk/tteokguk/tteokguk/constants/Ingredient.java
Labels: feat

#15 #13 이메일 로그인 API
  src/main/java/com/tteokguk/tteokguk/global/exception/ApiExceptionHandlingFilter.java
  src/main/java/com/tteokguk/tteokguk/global/security/SecurityConfig.java
  src/main/java/com/tteokguk/tteokguk/global/security/dto/WebLoginRequest.java
  src/main/java/com/tteokguk/tteokguk/global/security/dto/WebLoginResponse.java
  src/main/java/com/tteokguk/tteokguk/global/security/filter/CustomAuthenticationFilter.java
  src/main/java/com/tteokguk/tteokguk/global/security/filter/CustomAuthorizationFilter.java
  src/main/java/com/tteokguk/tteokguk/global/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/tteokguk/tteokguk/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/tteokguk/tteokguk/global/security/jwt/Jwt.java
  src/main/java/com/tteokguk/tteokguk/global/security/jwt/JwtFactory.java
  src/main/java/com/tteokguk/tteokguk/global/security/model/PrincipalDetails.java
  src/main/java/com/tteokguk/tteokguk/global/security/provider/CustomAuthenticationProvider.java
  src/main/java/com/tteokguk/tteokguk/member/exception/AuthError.java
  src/main/java/com/tteokguk/tteokguk/member/infra/persistence/SimpleMemberRepository.java
Labels: feat

#17 #16 Github Actions CD 스크립트 수정
  .github/workflows/BuildTest.yml
  .github/workflows/dev-cd-jobs.yml
Labels: bug

#18 [FEATURE] #12 예외에 대한 세부 응답 추가
  src/main/java/com/tteokguk/tteokguk/global/exception/ApiExceptionHandler.java
  src/main/java/com/tteokguk/tteokguk/global/exception/error/ErrorResponse.java
  src/main/java/com/tteokguk/tteokguk/global/exception/error/GlobalError.java
Labels: feat

#14 #8-1 떡국 단순 생성 API
  src/main/java/com/tteokguk/tteokguk/global/constants/BooleanStatus.java
  src/main/java/com/tteokguk/tteokguk/member/domain/Inventory.java
  src/main/java/com/tteokguk/tteokguk/member/exception/MemberError.java
  src/main/java/com/tteokguk/tteokguk/member/infra/persistence/MemberRepository.java
  src/main/java/com/tteokguk/tteokguk/member/infra/persistence/SimpleMemberRepository.java
  src/main/java/com/tteokguk/tteokguk/tteokguk/Tteokguk.java
  src/main/java/com/tteokguk/tteokguk/tteokguk/TteokgukIngredient.java
  src/main/java/com/tteokguk/tteokguk/tteokguk/application/TteokgukService.java
  src/main/java/com/tteokguk/tteokguk/tteokguk/application/dto/request/CreateTteokgukRequest.java
  src/main/java/com/tteokguk/tteokguk/tteokguk/application/dto/response/CreateTteokgukResponse.java
  src/main/java/com/tteokguk/tteokguk/tteokguk/constants/Ingredient.java
  src/main/java/com/tteokguk/tteokguk/tteokguk/domain/Tteokguk.java
  src/main/java/com/tteokguk/tteokguk/tteokguk/exception/TteokgukError.java
  src/main/java/com/tteokguk/tteokguk/tteokguk/infra/persistence/TteokgukRepository.java
  src/main/java/com/tteokguk/tteokguk/tteokguk/presentation/TteokgukController.java
Labels: feat

#31 feat: 타 유저 단순 조회 API
  src/main/java/com/tteokguk/tteokguk/member/application/ItemService.java
  src/main/java/com/tteokguk/tteokguk/member/application/UserInfoService.java
  src/main/java/com/tteokguk/tteokguk/member/application/dto/response/UserInfoResponse.java
  src/main/java/com/tteokguk/tteokguk/member/application/dto/response/assembler/UserInfoResponseAssembler.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/MyPageController.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/UserInfoController.java
Labels: feat

#37 [FIX] #34 로그인한 유저의 ID값이 스트링인 오류 해결
  src/main/java/com/tteokguk/tteokguk/global/security/annotation/AuthId.java
  src/main/java/com/tteokguk/tteokguk/global/security/jwt/Jwt.java
  src/main/java/com/tteokguk/tteokguk/global/security/model/CustomUser.java
Labels: fix

#39 [FIX] #27 회원가입 시 마케팅 활용 정보 동의 필드 추가
  src/main/java/com/tteokguk/tteokguk/member/application/AuthService.java
  src/main/java/com/tteokguk/tteokguk/member/application/OAuthService.java
  src/main/java/com/tteokguk/tteokguk/member/application/dto/request/AppJoinRequest.java
  src/main/java/com/tteokguk/tteokguk/member/domain/Member.java
  src/main/java/com/tteokguk/tteokguk/member/domain/OAuthMember.java
  src/main/java/com/tteokguk/tteokguk/member/domain/SimpleMember.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/dto/WebJoinRequest.java
Labels: fix

#40 [FIX] #36 쿠키에 redirect_url이 없는 경우 에러 메시지 반환
  src/main/java/com/tteokguk/tteokguk/member/exception/AuthError.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/OAuthController.java
Labels: fix

#42 [FEATURE] #41 임시 유저 초기화 API
  src/main/java/com/tteokguk/tteokguk/global/security/SecurityConfig.java
  src/main/java/com/tteokguk/tteokguk/global/security/matcher/CustomRequestMatcher.java
  src/main/java/com/tteokguk/tteokguk/member/application/AuthService.java
  src/main/java/com/tteokguk/tteokguk/member/application/UserInfoService.java
  src/main/java/com/tteokguk/tteokguk/member/application/dto/request/AppInitRequest.java
  src/main/java/com/tteokguk/tteokguk/member/application/dto/response/AppInitResponse.java
  src/main/java/com/tteokguk/tteokguk/member/domain/Member.java
  src/main/java/com/tteokguk/tteokguk/member/exception/AuthError.java
  src/main/java/com/tteokguk/tteokguk/member/exception/MemberError.java
  src/main/java/com/tteokguk/tteokguk/member/infra/persistence/MemberRepository.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/UserInfoController.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/dto/WebInitRequest.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/dto/WebInitResponse.java
Labels: feat

#50 [FEATURE] #44 토큰 재발급 API 생성
  src/main/java/com/tteokguk/tteokguk/global/security/handler/CustomAuthenticationSuccessHandler.java
  src/main/java/com/tteokguk/tteokguk/global/security/jwt/JwtService.java
  src/main/java/com/tteokguk/tteokguk/global/utils/LocalDateTimeUtils.java
  src/main/java/com/tteokguk/tteokguk/member/application/OAuthService.java
  src/main/java/com/tteokguk/tteokguk/member/application/RefreshTokenService.java
  src/main/java/com/tteokguk/tteokguk/member/application/dto/response/AppIssuedTokensResponse.java
  src/main/java/com/tteokguk/tteokguk/member/domain/RefreshToken.java
  src/main/java/com/tteokguk/tteokguk/member/exception/AuthError.java
  src/main/java/com/tteokguk/tteokguk/member/infra/persistence/RefreshTokenRepository.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/AuthController.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/dto/WebIssuedTokensRequest.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/dto/WebIssuedTokensResponse.java
Labels: feat

#51 [FIX] #43 중복 체크 API 파라미터 예외 응답 추가 및 4XX, 5XX 예외 관련 버그 수정
  src/main/java/com/tteokguk/tteokguk/global/security/SecurityConfig.java
  src/main/java/com/tteokguk/tteokguk/global/security/matcher/CustomRequestMatcher.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/AuthController.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/dto/WebCheckEmailRequest.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/dto/WebCheckNicknameRequest.java
Labels: fix

#58 [FEATURE] #53 유저 탈퇴 API
  src/main/java/com/tteokguk/tteokguk/member/application/UserInfoService.java
  src/main/java/com/tteokguk/tteokguk/member/domain/Member.java
  src/main/java/com/tteokguk/tteokguk/member/domain/OAuthMember.java
  src/main/java/com/tteokguk/tteokguk/member/domain/SimpleMember.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/UserInfoController.java
Labels: feat

#60 [FEATURE] #54 닉네임을 통한 유저 조회 API
  src/main/java/com/tteokguk/tteokguk/member/application/UserInfoService.java
  src/main/java/com/tteokguk/tteokguk/member/infra/persistence/MemberRepository.java
  src/main/java/com/tteokguk/tteokguk/member/presentation/UserInfoController.java
Labels: feat
